
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./anigame-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: pg

      FRONTEND_URL: http://localhost
      FRONTEND_PORT: 8085
      FRONTEND_VERRIFY_ENDPOINT: /auth/verify-user

      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIl_USERNAME: lucas.tibetano@gmail.com
      EMAIL_PASSWORD: lrpcalbooydpshul



    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./anigame-app
      dockerfile: Dockerfile
      args:
        VITE_API_HOST: localhost
        VITE_API_PORT: 8080
    ports:
      - "8085:80"
      


#volumes:
#  postgres_data:
