server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lucas.tibetano@gmail.com
    password: lrpcalbooydpshul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  #jpa:
    #hibernate:
    #  ddl-auto: create-drop
    #  ddl-auto: update
    #show-sql: true
    #defer-datasource-initialization: true
    #properties:
    #  hibernate:
    #    format_sql: true
app:
  url: http://localhost
  port: 8085
  verify-endpoint: /auth/verify-email

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600
  refresh-token: 28800