server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: anigame.staff@gmail.com
    password: rlejhptrghlsbgde
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #jpa:
    #hibernate:
    #  ddl-auto: create-drop
    #  ddl-auto: update
    #show-sql: true
    #defer-datasource-initialization: true
    #properties:
    #  hibernate:
    #    format_sql: true
app:
  url: http://localhost
  port: 8085
  verify-email-endpoint: /auth/verify-user
  new-password-endpoint: /auth/new-password

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600
  refresh-token: 28800