ALTER TABLE tb_users
ADD COLUMN status VARCHAR(80) NOT NULL DEFAULT 'PENDING'
CHECK (status IN ('PENDING', 'CONFIRMED')),
ADD COLUMN validation_token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
ADD COLUMN validation_token_expiration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
